# Generated by Django 5.0.7 on 2024-07-30 04:52

import mealPlannerApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealPlannerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='macros',
            options={'verbose_name_plural': 'Macros'},
        ),
        migrations.AlterField(
            model_name='macros',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[mealPlannerApp.models.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='macros',
            name='fat',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[mealPlannerApp.models.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='macros',
            name='name',
            field=models.CharField(max_length=100, validators=[mealPlannerApp.models.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='macros',
            name='protein',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[mealPlannerApp.models.validate_non_empty]),
        ),
    ]
