# Generated by Django 5.0.7 on 2024-07-30 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealPlannerApp', '0003_alter_macros_carbs_alter_macros_fat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('protein', models.DecimalField(decimal_places=0, max_digits=4)),
                ('fat', models.DecimalField(decimal_places=0, max_digits=4)),
                ('carbs', models.DecimalField(decimal_places=0, max_digits=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
