# Generated by Django 5.0.7 on 2024-07-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealPlannerApp', '0004_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='units',
            field=models.CharField(default='units', max_length=100),
            preserve_default=False,
        ),
    ]
